# Service
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: movies-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-api
  template:
    metadata:
      labels:
        app: movies-api
    spec:
      containers:
        - name: movies-api-container
          image: arunnjoshi/movies-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 
