services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=movies
      - POSTGRES_USER=course
    ports:
      - "5432:5432"
